name: 'Godot Android Export'
description: 'Godot Engine 3.x and 4.x Android export'
author: 'Simon Dalvai @dulvui'
branding:
  color: blue
  icon: upload-cloud

inputs:
  godot-version:
    description: 'Godot Engine version'
    required: true
  godot-channel:
    description: 'Godot Engine release channel (stable, beta, rc1, rc2, rc3...). Defaults to stable.'
    required: false
    default: 'stable'
  working-directory:
    description: 'The working directory'
    required: false
    default: '.'
  
runs:
  using: "composite"
  steps:
    - name: Set up Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Cache Godot files
      id: cache-godot
      uses: actions/cache@v3
      with:
        path: |
          ~/.local/share/godot/**
          /usr/local/bin/godot
          ~/.config/godot/**
        key: ${{ runner.os }}-godot-${{ inputs.godot-version }}-${{ inputs.godot-channel }}

    - name: Download and config Godot Engine headless linux server and templates
      if: steps.cache-godot.outputs.cache-hit != 'true'
      shell: bash
      run: |
        wget -q https://github.com/godotengine/godot-builds/releases/download/${{ inputs.godot-version }}-${{ inputs.godot-channel}}/Godot_v${{ inputs.godot-version }}-${{ inputs.godot-channel }}_linux_headless.64.zip
        wget -q https://github.com/godotengine/godot-builds/releases/download/${{ inputs.godot-version }}-${{ inputs.godot-channel}}/Godot_v${{ inputs.godot-version }}-${{ inputs.godot-channel }}_export_templates.tpz
        unzip Godot_v${{ inputs.godot-version }}-${{ inputs.godot-channel }}_linux_headless.64.zip
        unzip Godot_v${{ inputs.godot-version }}-${{ inputs.godot-channel }}_export_templates.tpz
        mkdir -p ~/.local/share/godot/export_templates/${{ inputs.godot-version }}.${{ inputs.godot-channel }}
        mkdir -p ~/.config/godot
        mv Godot_v${{ inputs.godot-version }}-${{ inputs.godot-channel }}_linux_headless.64 /usr/local/bin/godot
        mv templates/* ~/.local/share/godot/templates/${{ inputs.godot-version }}.${{ inputs.godot-channel }}
        rm -f Godot_v${{ inputs.godot-version }}-${{ inputs.godot-channel }}_linux_headless.64.zip Godot_v${{ inputs.godot-version }}-${{ inputs.godot-channel }}_export_templates.tpz

    - name: Set Android SDK path in Godot Editor settings
      if: steps.cache-godot.outputs.cache-hit != 'true'
      shell: bash
      env:
        SETTINGS: |
          export/android/android_sdk_path = "/usr/local/lib/android/sdk"
          export/android/shutdown_adb_on_exit = true
          export/android/force_system_user = false
      run: echo $SETTINGS >> ~/.config/godot/editor_settings-3.tres

    - name: Install Android build template
      shell: bash
      run: |
        mkdir -p ${{ inputs.working-directory }}/android/plugins
        mkdir -p ${{ inputs.working-directory }}/android/build
        touch ${{ inputs.working-directory }}/android/build/.gdignore
        echo ${{ inputs.godot-version }}.${{ inputs.godot-channel }} >> ${{ inputs.working-directory }}/android/.build_version
        unzip ~/.local/share/godot/templates/${{ inputs.godot-version }}.${{ inputs.godot-channel }}/android_source.zip  -d ${{ inputs.working-directory }}/android/build

    - name: Open project once to import assets in editor mode
      shell: bash
      continue-on-error: true # timeout will exit with code 124
      run: timeout 25 godot --path ${{ inputs.working-directory }} -e

    - name: Export
      shell: bash
      run: godot --path ${{ inputs.working-directory }} --export Android
